name: Deploy to Netlify

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Restore bestdori responses
        uses: actions/cache/restore@v4
        with:
          path: |
            bestdori/*.json
            bestdori/*.png
          key: bestdori-response-
      - name: Restore compressed assets
        uses: actions/cache/restore@v4
        with:
          path: bestdori/compressed/
          key: compressed-bestdori-asset-${{ hashFiles('src/lib/bestdori/compress.ts') }}-

      - name: Build site
        run: bun run build

      - name: Save bestdori responses cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            bestdori/*.json
            bestdori/*.png
          key: bestdori-response-${{ github.run_id }}-${{ github.run_number }}
      - name: Save compressed assets cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: bestdori/compressed/
          key: compressed-bestdori-asset-${{ hashFiles('src/lib/bestdori/compress.ts') }}-${{ github.run_id }}-${{ github.run_number }}

      - name: Upload bestdori responses
        uses: actions/upload-artifact@v4
        with:
          name: bestdori-${{ github.run_id }}
          path: |
            bestdori/*.json
            bestdori/*.png
      - name: Upload compressed assets
        uses: actions/upload-artifact@v4
        with:
          name: compressed-bestdori-${{ github.run_id }}
          path: bestdori/compressed/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: netlify-site
          include-hidden-files: true
          path: |
            .netlify/
            dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: netlify-site
      url: ${{ steps.netlify_deployment.outputs.url }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: netlify-site

      - name: Deploy to Netlify
        id: netlify_deployment
        run: |
          url=$(bun run deploy --json | jq -r .url)
          echo "url=$url" >> $GITHUB_OUTPUT
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
